In [1]:
import torch

def is_overlapping(box1, box2):

  # Ensure both tensors have the same dimensionality (N, 4) and device
  box1 = box1.view(-1, 4).to(box2.device)
  box2 = box2.view(-1, 4).to(box1.device)

  # Calculate the area of overlap for all box pairs
  conditions = [
      box1[:, 0] < box2[:, 2],  # x1 of box1 < x2 of box2
      box1[:, 1] < box2[:, 3],  # y1 of box1 < y2 of box2
      box1[:, 2] > box2[:, 0],  # x2 of box1 > x1 of box2
      box1[:, 3] > box2[:, 1]   # y2 of box1 > y1 of box2
  ]
  intersection = torch.all(torch.stack(conditions), dim=0)

  return intersection

# Example usage
box1 = torch.tensor([[1, 2, 4, 5], [3, 1, 5, 4]])
box2 = torch.tensor([[2, 3, 5, 6], [0, 0, 7, 7]])

overlap_matrix = is_overlapping(box1, box2)
print(overlap_matrix)


tensor([True, True])


In [ ]:
import torch

def intersection_area(boxes1, boxes2):
  """
  Calculates the intersection area between two tensors of bounding boxes.

  Args:
      boxes1: A torch tensor of shape (batch_size, 4) representing bounding boxes 
              with format [x1, y1, x2, y2].
      boxes2: A torch tensor of the same shape as boxes1.

  Returns:
      A torch tensor of shape (batch_size,) representing the intersection area 
      for each bounding box in the batch.
  """
  # Get the top left corner coordinates for both boxes
  tl_x1 = torch.max(boxes1[:, 0], boxes2[:, 0])
  tl_y1 = torch.max(boxes1[:, 1], boxes2[:, 1])

  # Get the bottom right corner coordinates for both boxes
  br_x2 = torch.min(boxes1[:, 2], boxes2[:, 2])
  br_y2 = torch.min(boxes1[:, 3], boxes2[:, 3])

  # Ensure width and height are non-negative (no intersection)
  intersection_width = torch.clamp(br_x2 - tl_x1, min=0)
  intersection_height = torch.clamp(br_y2 - tl_y1, min=0)

  # Calculate the intersection area
  intersection_area = intersection_width * intersection_height

  return intersection_area

# Example usage
boxes1 = torch.tensor([[1, 2, 4, 5], [3, 4, 6, 7]])
boxes2 = torch.tensor([[2, 3, 5, 6], [1, 1, 5, 5]])

intersection_areas = intersection_area(boxes1, boxes2)
print(intersection_areas)


In [11]:
import torch 

data = torch.Tensor([[1, 5, 4, 2, 3], [9, 6, 6, 7, 1]])
b = torch.sort(a, descending=False).values
print(b)
print(type(a))
print(type(b))

tensor([[1., 2., 3., 4., 5.],
        [1., 5., 6., 7., 9.]])
<class 'torch.Tensor'>
<class 'torch.Tensor'>


In [15]:
sorted_data = torch.tensor(sorted(data.numpy(), key=lambda x: x[1]))
print(sorted_data)

tensor([[1., 5., 4., 2., 3.],
        [9., 6., 6., 7., 1.]])


In [14]:
torch.tensor(b.numpy())

tensor([[1., 2., 3., 4., 5.],
        [1., 5., 6., 7., 9.]])